services:
  postgres:
    image: postgres:alpine
    container_name: flatmatedb
    environment:
      POSTGRES_DB: flatmatedb
      POSTGRES_USER: flatmate
      POSTGRES_PASSWORD: flatmate
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 