version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: flatmatedb
    environment:
      POSTGRES_DB: flatmatedb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
